### zprofile

# global environment variables
export LC_ALL="en_US.UTF-8"
export DEFAULT_USER=mateck
export EDITOR=nvim
export VISUAL=nvim
export TERMINAL=alacritty
export BROWSER=firefox
export MOZ_ENABLE_WAYLAND=1

# Rust libs
PATH="${PATH:+${PATH}:}$HOME/.cargo/bin"
# Ruby gems
PATH="${PATH:+${PATH}:}$(ruby -e 'print Gem.user_dir')/bin"
# Vivado
PATH="${PATH:+${PATH}:}/opt/Xilinx/Vivado/2018.3/bin"

# antigen variables
export ADOTDIR=~/.config/antigen

# ranger variables
export RANGER_LOAD_DEFAULTS_RC=FALSE

export WLR_DRM_NO_MODIFIERS=1

# Aliases
alias diff='diff --color=auto'
alias grep='grep --color=auto'
alias ls='ls --color=auto'

# Launching sway
if [ -z "$DISPLAY" ] && [ $(tty) = /dev/tty1 ]; then
	sway
fi
