#!/bin/zsh

# global environment variables
export LC_ALL="en_US.UTF-8"
export DEFAULT_USER=mateck
export EDITOR=nvim
export VISUAL=nvim
export TERMINAL=alacritty
export BROWSER=firefox

# python
export PIP_USER=yes
# rust cargo
PATH="${PATH:+${PATH}:}$HOME/.cargo/bin"
# ruby gems
PATH="${PATH:+${PATH}:}$(ruby -e 'print Gem.user_dir')/bin"
# vivado
PATH="${PATH:+${PATH}:}/opt/Xilinx/Vivado/2018.3/bin"
# zephyr
ZEPHYR_ENV_SH=$HOME/bin/zephyr/zephyr/zephyr-env.sh
if [ -f "$ZEPHYR_ENV_SH" ]; then
    source $ZEPHYR_ENV_SH
fi

# antigen variables
export ADOTDIR=$HOME/.config/antigen

# ranger variables
export RANGER_LOAD_DEFAULTS_RC=FALSE

# launch x server
if [ -z "$DISPLAY" ] && [ $(tty) = /dev/tty1 ]; then
    startx
fi

