### zprofile

# global environment variables
export LC_ALL="en_US.UTF-8"
export DEFAULT_USER=mateck
export EDITOR=nvim
export VISUAL=nvim
export TERMINAL=termite
export BROWSER=firefox

# Ruby gems
PATH="$PATH:$(ruby -e 'print Gem.user_dir')/bin"
# Vivado
PATH="$PATH:/opt/Xilinx/Vivado/2018.3/bin"

# antigen variables
export ADOTDIR=~/.config/antigen

# ranger variables
export RANGER_LOAD_DEFAULTS_RC=FALSE

# Aliases
alias diff='diff --color=auto'
alias grep='grep --color=auto'
alias ls='ls --color=auto'

# Launching xorg
if [ -z "$DISPLAY" ] && [ -n "$XDG_VTNR" ] && [ "$XDG_VTNR" -eq 1 ]; then
	startx
fi
