### zprofile

export EDITOR=nvim
export VISUAL=nvim
export TERMINAL=termite
export BROWSER=firefox

export RANGER_LOAD_DEFAULTS_RC=FALSE

alias diff='diff --color=auto'
alias grep='grep --color=auto'
alias ls='ls --color=auto'

if [ -z "$DISPLAY" ] && [ -n "$XDG_VTNR" ] && [ "$XDG_VTNR" -lt 3 ]; then
	sway
fi
